# Generated by Django 4.0.4 on 2022-06-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'my_product',
            },
        ),
    ]
